export const Gents = {
    title : "Gents Fashion",
    image1: "assests/Men/1.jpeg",
    image2: "assests/Men/2.jpeg",
    image3: "assests/Men/3.jpeg",
    image4: "assests/Men/4.jpeg",
    image5: "assests/Men/5.jpeg",
    image6: "assests/Men/6.jpeg",
    image7: "assests/Men/7.jpeg",
    image8: "assests/Men/8.jpeg",
    price1: "559INR",
    price2: "559INR",
    price3: "559INR",
    price4: "559INR",
    price5: "559INR",
    price6: "559INR",
    price7: "559INR",
    price8: "559INR",
}

export const Ladies ={
    title : "Ladies Fashion",
    image1: "assests/Women/1.jpeg",
    image2: "assests/Women/2.jpeg",
    image3: "assests/Women/3.jpeg",
    image4: "assests/Women/4.jpeg",
    image5: "assests/Women/5.jpeg",
    image6: "assests/Women/6.jpeg",
    image7: "assests/Women/7.jpeg",
    image8: "assests/Women/8.jpeg",
    price1: "559INR",
    price2: "559INR",
    price3: "559INR",
    price4: "559INR",
    price5: "559INR",
    price6: "559INR",
    price7: "559INR",
    price8: "559INR",
}